import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";


const inter = Inter({ subsets: ["latin"] });

const links = [
  { href: '/', nombre: 'Home' },
  { href: '/about', nombre: 'Search' },
  { href: '/contact', nombre: 'File Explorer' },
];

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavBar links={links} />
        {children}</body>
    </html>
  );
}
